version: '3.3'

services:
  db:
    image: postgres:14.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - .env
  backend:
    image: daniilpanyushin/cloud_file_storage:0.1
#    build:
#      context: ../..
#      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
#      - static_files:/code/static/
      - media_files:/code/media/
    depends_on:
      - db

volumes:
  postgres_data:
#  static_files:
  media_files: