apiVersion: v1
kind: Service
metadata:
  name: backend-balancer
  labels:
    app: backend
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: backend